#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    x=' '
    y='#'
    i =1 
    while i <= n:
        print((n-i)*x+i*y)
        i += 1

if __name__ == '__main__':
    n = int(input())

    staircase(n)
